version: "3.9"

services:
  app:
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
    command:
      - sh
      - -c
      - |
        echo "This container will stop after ending the python job"
        python main.py